behaviors:
    Node_AI:
        trainer_type: sac
        summary_freq: 50000
        time_horizon: 128
        max_steps: 5.0e6
        keep_checkpoints: 5
        checkpoint_interval: 500000
        init_path: none
        threaded: true
        hyperparameters:
            learning_rate: 3e-4
            batch_size: 100 #this is a guess avg is 32 - 512
            buffer_size: 50000
            learning_rate_schedule: constant
            buffer_init_steps: 0
            init_entcoef: 0.5
            save_replay_buffer: true
            tau: 0.005
            steps_per_update: 1
            reward_signal_num_update: steps_per_update
        network_settings:
            hidden_units: 256
            num_layers: 2 #typical is 1 - 3
            normalize: false
            vis_encoder_type: match3
        curiosity:
            strength: 0.05
            gamma: 0.99
            encoding_size: 64
            learning_rate: 3e-4
        save_steps: 20000
        team_change: 4 * save_steps
        swap_steps: 5000
        play_against_latest_model_ratio: 0.5
        window: 10
